### ISSUE TITLE
Crash if trait not filled correctly

### ISSUE THREAD

**Issue by glsf91** [i8beef/HomeAutio.Mqtt.GoogleHome#126]
I use 2.0.0.163
I added a device. I also added a trait OnOff without filling the attribute, command and state field.
When saving the trait, the process crashed and I have manually to repair the googleDevices.json.

I got the following stack trace:

```
2021-01-11 20:03:30.203 +01:00 [INF] Executing RedirectResult, redirecting to /GoogleDevice/Edit?deviceId=test123.
2021-01-11 20:03:30.203 +01:00 [INF] Executed action HomeAutio.Mqtt.GoogleHome.Controllers.GoogleTraitController.Edit (HomeAutio.Mqtt.GoogleHome) in 53.3442ms
2021-01-11 20:03:30.203 +01:00 [INF] Executed endpoint 'HomeAutio.Mqtt.GoogleHome.Controllers.GoogleTraitController.Edit (HomeAutio.Mqtt.GoogleHome)'
2021-01-11 20:03:30.203 +01:00 [INF] Request finished HTTP/1.1 POST http://xxx.xxx:8443/GoogleTrait/Edit?deviceId=test123&traitId=action.devices.traits.OnOff application/x-www-form-urlencoded 298 - 302 0 - 59.1024ms
2021-01-11 20:03:40.886 +01:00 [INF] Loaded with configuration from: appsettings.json, /home/john/HomeAutio.Mqtt.GoogleHome/config/appsettings.Production.json
2021-01-11 20:03:41.424 +01:00 [INF] Starting IdentityServer4 version 4.1.1+cebd52f5bc61bdefc262fd20739d4d087c6f961f
2021-01-11 20:03:41.520 +01:00 [INF] Restored tokens from config/tokens.json
2021-01-11 20:03:41.545 +01:00 [INF] Using the default authentication scheme Cookies for IdentityServer
2021-01-11 20:03:42.152 +01:00 [INF] Loaded device configuration from config/googleDevices.json
2021-01-11 20:03:42.160 +01:00 [FTL] Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HomeAutio.Mqtt.GoogleHome.Startup.<>c.<ConfigureServices>b__4_15(DeviceTrait trait) in /home/john/HomeAutio.Mqtt.GoogleHome/src/HomeAutio.Mqtt.GoogleHome/Startup.cs:line 83
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at HomeAutio.Mqtt.GoogleHome.Startup.<>c.<ConfigureServices>b__4_1(IServiceProvider serviceProvider) in /home/john/HomeAutio.Mqtt.GoogleHome/src/HomeAutio.Mqtt.GoogleHome/Startup.cs:line 88
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at HomeAutio.Mqtt.GoogleHome.Program.Main(String[] args) in /home/john/HomeAutio.Mqtt.GoogleHome/src/HomeAutio.Mqtt.GoogleHome/Program.cs:line 45
```

So when making a little mistake in the trait fields it crashes and need manual to repair.

**Comment by i8beef** [comment]
Good find, Ill put out a fix that will at least allow this to start in this situation.

**Comment by i8beef** [comment]
See newest release 2.0.0.165

**Comment by i8beef** [comment]
Closing as fixed, please reopen if you have further issues.
